### ISSUE TITLE
LocaleChildrenFilter not available?

### ISSUE THREAD

**Issue by krisimmig** [optimistdigital/nova-locale-field#3]
I was testing this package and got stuck trying to implement the `LocaleChildrenFilter`. I also can't find it in the source. Is this already implemented?

**Comment by Tarpsvo** [comment]
Oh hey! Sorry about that, the LocaleChildrenFilter was removed a while back as it was replaced by the general LocaleFilter.

It basically did the same thing as selecting the empty value (`-`) on the LocaleFilter (displayed all the models).

Sorry about the confusion!
