### ISSUE TITLE
Adding default locales in boot method not working

### ISSUE THREAD

**Issue by krisimmig** [optimistdigital/nova-locale-field#4]
I can't get the recommended way to add default locales to work. Adding them in the `NovaServiceProvider` file via the `getLocales` method is not working.

When I insepct the code of `getLocales` it looks like a callback is not called at all, only from the config file. Adding it there like this works:
```php
    'locales' => function() {
        return \App\Language::all()->pluck('title', 'shortcode')->toArray();
    },
```

Is this maybe just an outdated readme issue?

**Comment by Tarpsvo** [comment]
Ah, yes. The README.md contains outdated information, sorry abut that! Currently, the only way to add locales is via the config file.
